Repository govCMS/GovCMS8, pull requests merged in 2020-06, with the labels that each got.

#435 [GOVCMSD8-453] Add minisite 8.x-1.3
  composer.json
Labels: Module

#418 [GOVCMSD8-517] Update token module to 1.7 (from 1.5)
  composer.json
Labels: Drupal 9 Ready

#410 [GOVCMSD8-461] update config filter module to 1.5 (from 1.4)
  composer.json
Labels: Drupal 9 Ready

#392 [GOVCMSD8-545] Update Entity Class Formatter module from 1.1 to 1.3.
  composer.json
Labels: Needs Testing
